// Code generated by protoc-gen-go. DO NOT EDIT.
// source: captcha_digit.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CaptchaDigitCfg struct {
	Height               int32    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	MaxSkew              int32    `protobuf:"varint,3,opt,name=maxSkew,proto3" json:"maxSkew,omitempty"`
	DotCount             int32    `protobuf:"varint,4,opt,name=dotCount,proto3" json:"dotCount,omitempty"`
	CaptchaLen           int32    `protobuf:"varint,5,opt,name=captchaLen,proto3" json:"captchaLen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CaptchaDigitCfg) Reset()         { *m = CaptchaDigitCfg{} }
func (m *CaptchaDigitCfg) String() string { return proto.CompactTextString(m) }
func (*CaptchaDigitCfg) ProtoMessage()    {}
func (*CaptchaDigitCfg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d12d530c1b0e06, []int{0}
}

func (m *CaptchaDigitCfg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaptchaDigitCfg.Unmarshal(m, b)
}
func (m *CaptchaDigitCfg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaptchaDigitCfg.Marshal(b, m, deterministic)
}
func (m *CaptchaDigitCfg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaptchaDigitCfg.Merge(m, src)
}
func (m *CaptchaDigitCfg) XXX_Size() int {
	return xxx_messageInfo_CaptchaDigitCfg.Size(m)
}
func (m *CaptchaDigitCfg) XXX_DiscardUnknown() {
	xxx_messageInfo_CaptchaDigitCfg.DiscardUnknown(m)
}

var xxx_messageInfo_CaptchaDigitCfg proto.InternalMessageInfo

func (m *CaptchaDigitCfg) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *CaptchaDigitCfg) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *CaptchaDigitCfg) GetMaxSkew() int32 {
	if m != nil {
		return m.MaxSkew
	}
	return 0
}

func (m *CaptchaDigitCfg) GetDotCount() int32 {
	if m != nil {
		return m.DotCount
	}
	return 0
}

func (m *CaptchaDigitCfg) GetCaptchaLen() int32 {
	if m != nil {
		return m.CaptchaLen
	}
	return 0
}

func init() {
	proto.RegisterType((*CaptchaDigitCfg)(nil), "pb.CaptchaDigitCfg")
}

func init() { proto.RegisterFile("captcha_digit.proto", fileDescriptor_f8d12d530c1b0e06) }

var fileDescriptor_f8d12d530c1b0e06 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x4e, 0x2c, 0x28,
	0x49, 0xce, 0x48, 0x8c, 0x4f, 0xc9, 0x4c, 0xcf, 0x2c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x2a, 0x48, 0x52, 0x9a, 0xca, 0xc8, 0xc5, 0xef, 0x0c, 0x91, 0x73, 0x01, 0x49, 0x39, 0xa7,
	0xa5, 0x0b, 0x89, 0x71, 0xb1, 0x65, 0xa4, 0x66, 0xa6, 0x67, 0x94, 0x48, 0x30, 0x2a, 0x30, 0x6a,
	0xb0, 0x06, 0x41, 0x79, 0x42, 0x22, 0x5c, 0xac, 0xe5, 0x99, 0x29, 0x25, 0x19, 0x12, 0x4c, 0x60,
	0x61, 0x08, 0x47, 0x48, 0x82, 0x8b, 0x3d, 0x37, 0xb1, 0x22, 0x38, 0x3b, 0xb5, 0x5c, 0x82, 0x19,
	0x2c, 0x0e, 0xe3, 0x0a, 0x49, 0x71, 0x71, 0xa4, 0xe4, 0x97, 0x38, 0xe7, 0x97, 0xe6, 0x95, 0x48,
	0xb0, 0x80, 0xa5, 0xe0, 0x7c, 0x21, 0x39, 0x2e, 0x2e, 0xa8, 0x93, 0x7c, 0x52, 0xf3, 0x24, 0x58,
	0xc1, 0xb2, 0x48, 0x22, 0x49, 0x6c, 0x60, 0x27, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x36,
	0x28, 0xe1, 0xdb, 0xb9, 0x00, 0x00, 0x00,
}
