// Code generated by protoc-gen-go. DO NOT EDIT.
// source: create_room.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CtsCreateRoom struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CtsCreateRoom) Reset()         { *m = CtsCreateRoom{} }
func (m *CtsCreateRoom) String() string { return proto.CompactTextString(m) }
func (*CtsCreateRoom) ProtoMessage()    {}
func (*CtsCreateRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_7698b913de26b465, []int{0}
}

func (m *CtsCreateRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CtsCreateRoom.Unmarshal(m, b)
}
func (m *CtsCreateRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CtsCreateRoom.Marshal(b, m, deterministic)
}
func (m *CtsCreateRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CtsCreateRoom.Merge(m, src)
}
func (m *CtsCreateRoom) XXX_Size() int {
	return xxx_messageInfo_CtsCreateRoom.Size(m)
}
func (m *CtsCreateRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_CtsCreateRoom.DiscardUnknown(m)
}

var xxx_messageInfo_CtsCreateRoom proto.InternalMessageInfo

func (m *CtsCreateRoom) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type StcCreateRoom struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RoomId               int64    `protobuf:"varint,3,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StcCreateRoom) Reset()         { *m = StcCreateRoom{} }
func (m *StcCreateRoom) String() string { return proto.CompactTextString(m) }
func (*StcCreateRoom) ProtoMessage()    {}
func (*StcCreateRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_7698b913de26b465, []int{1}
}

func (m *StcCreateRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StcCreateRoom.Unmarshal(m, b)
}
func (m *StcCreateRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StcCreateRoom.Marshal(b, m, deterministic)
}
func (m *StcCreateRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StcCreateRoom.Merge(m, src)
}
func (m *StcCreateRoom) XXX_Size() int {
	return xxx_messageInfo_StcCreateRoom.Size(m)
}
func (m *StcCreateRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_StcCreateRoom.DiscardUnknown(m)
}

var xxx_messageInfo_StcCreateRoom proto.InternalMessageInfo

func (m *StcCreateRoom) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *StcCreateRoom) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func init() {
	proto.RegisterType((*CtsCreateRoom)(nil), "pb.CtsCreateRoom")
	proto.RegisterType((*StcCreateRoom)(nil), "pb.StcCreateRoom")
}

func init() { proto.RegisterFile("create_room.proto", fileDescriptor_7698b913de26b465) }

var fileDescriptor_7698b913de26b465 = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x2e, 0x4a, 0x4d,
	0x2c, 0x49, 0x8d, 0x2f, 0xca, 0xcf, 0xcf, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a,
	0x48, 0x52, 0x52, 0xe7, 0xe2, 0x75, 0x2e, 0x29, 0x76, 0x06, 0xcb, 0x05, 0xe5, 0xe7, 0xe7, 0x0a,
	0x89, 0x71, 0xb1, 0x95, 0x16, 0xa7, 0x16, 0x79, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07,
	0x41, 0x79, 0x4a, 0xf6, 0x5c, 0xbc, 0xc1, 0x25, 0xc9, 0x84, 0x15, 0x82, 0xc4, 0x41, 0x76, 0x78,
	0xa6, 0x48, 0x30, 0x43, 0xc4, 0x21, 0xbc, 0x24, 0x36, 0xb0, 0xa5, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x5a, 0x38, 0x4f, 0xff, 0x89, 0x00, 0x00, 0x00,
}
