// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Header struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	SessionId            int64    `protobuf:"varint,3,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	ServiceId0           int32    `protobuf:"varint,4,opt,name=serviceId0,proto3" json:"serviceId0,omitempty"`
	ServiceId1           int32    `protobuf:"varint,5,opt,name=serviceId1,proto3" json:"serviceId1,omitempty"`
	Token                string   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	TokenExpiredTime     int64    `protobuf:"varint,7,opt,name=tokenExpiredTime,proto3" json:"tokenExpiredTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Header) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Header) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *Header) GetServiceId0() int32 {
	if m != nil {
		return m.ServiceId0
	}
	return 0
}

func (m *Header) GetServiceId1() int32 {
	if m != nil {
		return m.ServiceId1
	}
	return 0
}

func (m *Header) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Header) GetTokenExpiredTime() int64 {
	if m != nil {
		return m.TokenExpiredTime
	}
	return 0
}

type Message struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "pb.Header")
	proto.RegisterType((*Message)(nil), "pb.Message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x85, 0x49, 0x66, 0x9a, 0x61, 0xae, 0x3f, 0xc8, 0x45, 0x24, 0x0b, 0x91, 0xd2, 0x55, 0x71,
	0x51, 0x1c, 0x7d, 0x02, 0x17, 0x82, 0x5d, 0xb8, 0x09, 0xbe, 0xc0, 0xc4, 0x7b, 0xd1, 0x20, 0xd3,
	0x84, 0xa4, 0x8a, 0xbe, 0xa5, 0x8f, 0x24, 0xdc, 0x16, 0xfc, 0x99, 0xdd, 0x39, 0xe7, 0x83, 0x84,
	0xef, 0xc2, 0xd1, 0x8e, 0x4b, 0xd9, 0x3e, 0x73, 0x97, 0x72, 0x1c, 0x23, 0xea, 0xe4, 0x9b, 0x2f,
	0x05, 0xe6, 0x9e, 0xb7, 0xc4, 0x19, 0x8f, 0x41, 0x07, 0xb2, 0xaa, 0x56, 0x6d, 0xe5, 0x74, 0x20,
	0x3c, 0x03, 0xf3, 0x56, 0x38, 0xf7, 0x64, 0x75, 0xad, 0xda, 0x85, 0x9b, 0x1b, 0x9e, 0xc3, 0xba,
	0x70, 0x29, 0x21, 0x0e, 0x3d, 0xd9, 0x85, 0xa0, 0x9f, 0x01, 0x2f, 0x00, 0x0a, 0xe7, 0xf7, 0xf0,
	0xc4, 0x3d, 0x5d, 0xd9, 0xa5, 0xbc, 0xf6, 0x6b, 0xf9, 0xc3, 0x37, 0xb6, 0xfa, 0xc7, 0x37, 0x78,
	0x0a, 0xd5, 0x18, 0x5f, 0x79, 0xb0, 0xa6, 0x56, 0xed, 0xda, 0x4d, 0x05, 0x2f, 0xe1, 0x44, 0xc2,
	0xdd, 0x47, 0x0a, 0x99, 0xe9, 0x31, 0xec, 0xd8, 0xae, 0xe4, 0xeb, 0xbd, 0xbd, 0xb9, 0x85, 0xd5,
	0xc3, 0xe4, 0x89, 0x0d, 0x98, 0x17, 0x91, 0x13, 0xad, 0x83, 0x6b, 0xe8, 0x92, 0xef, 0x26, 0x5d,
	0x37, 0x13, 0x44, 0x58, 0xfa, 0x48, 0x9f, 0x22, 0x79, 0xe8, 0x24, 0x7b, 0x23, 0x07, 0xba, 0xf9,
	0x0e, 0x00, 0x00, 0xff, 0xff, 0xda, 0xfa, 0xef, 0xb8, 0x31, 0x01, 0x00, 0x00,
}
