// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Header struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	SessionId            int64    `protobuf:"varint,3,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	ServiceId0           int32    `protobuf:"varint,4,opt,name=serviceId0,proto3" json:"serviceId0,omitempty"`
	ServiceId1           int32    `protobuf:"varint,5,opt,name=serviceId1,proto3" json:"serviceId1,omitempty"`
	Token                string   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	TokenExpiredTime     int64    `protobuf:"varint,7,opt,name=tokenExpiredTime,proto3" json:"tokenExpiredTime,omitempty"`
	Broadcast            bool     `protobuf:"varint,8,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Header) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Header) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *Header) GetServiceId0() int32 {
	if m != nil {
		return m.ServiceId0
	}
	return 0
}

func (m *Header) GetServiceId1() int32 {
	if m != nil {
		return m.ServiceId1
	}
	return 0
}

func (m *Header) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Header) GetTokenExpiredTime() int64 {
	if m != nil {
		return m.TokenExpiredTime
	}
	return 0
}

func (m *Header) GetBroadcast() bool {
	if m != nil {
		return m.Broadcast
	}
	return false
}

type Message struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "pb.Header")
	proto.RegisterType((*Message)(nil), "pb.Message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0xc7, 0x49, 0x77, 0x9b, 0xdd, 0x1d, 0x3f, 0x90, 0x41, 0x24, 0x07, 0x91, 0xd2, 0x53, 0xf1,
	0x50, 0x5c, 0x7d, 0x02, 0x0f, 0x82, 0x3d, 0x78, 0x09, 0xbe, 0x40, 0xb3, 0x33, 0x68, 0x90, 0xdd,
	0x84, 0xa4, 0x8a, 0xbe, 0xb4, 0xcf, 0x20, 0x4e, 0x17, 0xea, 0xc7, 0x6d, 0xe6, 0xf7, 0x27, 0x64,
	0xfe, 0x3f, 0x38, 0xda, 0x72, 0xce, 0xfd, 0x13, 0xb7, 0x31, 0x85, 0x21, 0x60, 0x11, 0x5d, 0xfd,
	0xa9, 0x40, 0xdf, 0x73, 0x4f, 0x9c, 0xf0, 0x18, 0x0a, 0x4f, 0x46, 0x55, 0xaa, 0x29, 0x6d, 0xe1,
	0x09, 0xcf, 0x40, 0xbf, 0x66, 0x4e, 0x1d, 0x99, 0x42, 0xd8, 0x7e, 0xc3, 0x73, 0x58, 0x65, 0xce,
	0xd9, 0x87, 0x5d, 0x47, 0x66, 0x56, 0xa9, 0x66, 0x66, 0x27, 0x80, 0x17, 0x00, 0x99, 0xd3, 0x9b,
	0xdf, 0x70, 0x47, 0x57, 0x66, 0x2e, 0x2f, 0x7f, 0x90, 0x5f, 0xf9, 0xda, 0x94, 0x7f, 0xf2, 0x35,
	0x9e, 0x42, 0x39, 0x84, 0x17, 0xde, 0x19, 0x5d, 0xa9, 0x66, 0x65, 0xc7, 0x05, 0x2f, 0xe1, 0x44,
	0x86, 0xbb, 0xf7, 0xe8, 0x13, 0xd3, 0xa3, 0xdf, 0xb2, 0x59, 0xc8, 0xd7, 0xff, 0xf8, 0xf7, 0x7d,
	0x2e, 0x85, 0x9e, 0x36, 0x7d, 0x1e, 0xcc, 0xb2, 0x52, 0xcd, 0xd2, 0x4e, 0xa0, 0xbe, 0x85, 0xc5,
	0xc3, 0x68, 0x01, 0x6b, 0xd0, 0xcf, 0x52, 0x5d, 0x4a, 0x1f, 0x5c, 0x43, 0x1b, 0x5d, 0x3b, 0xca,
	0xb0, 0xfb, 0x04, 0x11, 0xe6, 0x2e, 0xd0, 0x87, 0x28, 0x38, 0xb4, 0x32, 0x3b, 0x2d, 0xfa, 0x6e,
	0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x70, 0xf7, 0xaa, 0xef, 0x4f, 0x01, 0x00, 0x00,
}
