// Code generated by protoc-gen-go. DO NOT EDIT.
// source: play_piece.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CtsPlayPiece struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	ChairId              int32    `protobuf:"varint,2,opt,name=chairId,proto3" json:"chairId,omitempty"`
	X                    int32    `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CtsPlayPiece) Reset()         { *m = CtsPlayPiece{} }
func (m *CtsPlayPiece) String() string { return proto.CompactTextString(m) }
func (*CtsPlayPiece) ProtoMessage()    {}
func (*CtsPlayPiece) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2e671f06c60228b, []int{0}
}

func (m *CtsPlayPiece) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CtsPlayPiece.Unmarshal(m, b)
}
func (m *CtsPlayPiece) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CtsPlayPiece.Marshal(b, m, deterministic)
}
func (m *CtsPlayPiece) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CtsPlayPiece.Merge(m, src)
}
func (m *CtsPlayPiece) XXX_Size() int {
	return xxx_messageInfo_CtsPlayPiece.Size(m)
}
func (m *CtsPlayPiece) XXX_DiscardUnknown() {
	xxx_messageInfo_CtsPlayPiece.DiscardUnknown(m)
}

var xxx_messageInfo_CtsPlayPiece proto.InternalMessageInfo

func (m *CtsPlayPiece) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *CtsPlayPiece) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *CtsPlayPiece) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *CtsPlayPiece) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type StcPlayPiece struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	ChairId              int32    `protobuf:"varint,2,opt,name=chairId,proto3" json:"chairId,omitempty"`
	X                    int32    `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StcPlayPiece) Reset()         { *m = StcPlayPiece{} }
func (m *StcPlayPiece) String() string { return proto.CompactTextString(m) }
func (*StcPlayPiece) ProtoMessage()    {}
func (*StcPlayPiece) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2e671f06c60228b, []int{1}
}

func (m *StcPlayPiece) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StcPlayPiece.Unmarshal(m, b)
}
func (m *StcPlayPiece) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StcPlayPiece.Marshal(b, m, deterministic)
}
func (m *StcPlayPiece) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StcPlayPiece.Merge(m, src)
}
func (m *StcPlayPiece) XXX_Size() int {
	return xxx_messageInfo_StcPlayPiece.Size(m)
}
func (m *StcPlayPiece) XXX_DiscardUnknown() {
	xxx_messageInfo_StcPlayPiece.DiscardUnknown(m)
}

var xxx_messageInfo_StcPlayPiece proto.InternalMessageInfo

func (m *StcPlayPiece) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *StcPlayPiece) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *StcPlayPiece) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *StcPlayPiece) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type StcGameResult struct {
	Winner               int32    `protobuf:"varint,1,opt,name=winner,proto3" json:"winner,omitempty"`
	Looser               int32    `protobuf:"varint,2,opt,name=looser,proto3" json:"looser,omitempty"`
	PieceList            []*Piece `protobuf:"bytes,3,rep,name=pieceList,proto3" json:"pieceList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StcGameResult) Reset()         { *m = StcGameResult{} }
func (m *StcGameResult) String() string { return proto.CompactTextString(m) }
func (*StcGameResult) ProtoMessage()    {}
func (*StcGameResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2e671f06c60228b, []int{2}
}

func (m *StcGameResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StcGameResult.Unmarshal(m, b)
}
func (m *StcGameResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StcGameResult.Marshal(b, m, deterministic)
}
func (m *StcGameResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StcGameResult.Merge(m, src)
}
func (m *StcGameResult) XXX_Size() int {
	return xxx_messageInfo_StcGameResult.Size(m)
}
func (m *StcGameResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StcGameResult.DiscardUnknown(m)
}

var xxx_messageInfo_StcGameResult proto.InternalMessageInfo

func (m *StcGameResult) GetWinner() int32 {
	if m != nil {
		return m.Winner
	}
	return 0
}

func (m *StcGameResult) GetLooser() int32 {
	if m != nil {
		return m.Looser
	}
	return 0
}

func (m *StcGameResult) GetPieceList() []*Piece {
	if m != nil {
		return m.PieceList
	}
	return nil
}

type Piece struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	X                    int32    `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Piece) Reset()         { *m = Piece{} }
func (m *Piece) String() string { return proto.CompactTextString(m) }
func (*Piece) ProtoMessage()    {}
func (*Piece) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2e671f06c60228b, []int{3}
}

func (m *Piece) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Piece.Unmarshal(m, b)
}
func (m *Piece) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Piece.Marshal(b, m, deterministic)
}
func (m *Piece) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Piece.Merge(m, src)
}
func (m *Piece) XXX_Size() int {
	return xxx_messageInfo_Piece.Size(m)
}
func (m *Piece) XXX_DiscardUnknown() {
	xxx_messageInfo_Piece.DiscardUnknown(m)
}

var xxx_messageInfo_Piece proto.InternalMessageInfo

func (m *Piece) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Piece) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Piece) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*CtsPlayPiece)(nil), "pb.CtsPlayPiece")
	proto.RegisterType((*StcPlayPiece)(nil), "pb.StcPlayPiece")
	proto.RegisterType((*StcGameResult)(nil), "pb.StcGameResult")
	proto.RegisterType((*Piece)(nil), "pb.Piece")
}

func init() { proto.RegisterFile("play_piece.proto", fileDescriptor_f2e671f06c60228b) }

var fileDescriptor_f2e671f06c60228b = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x90, 0xbf, 0x4b, 0x03, 0x31,
	0x14, 0x80, 0xc9, 0xc5, 0x54, 0xfa, 0xac, 0x20, 0x41, 0x24, 0xe3, 0xd1, 0xc5, 0x9b, 0x6e, 0xd0,
	0xc9, 0xd9, 0x41, 0x0a, 0x0e, 0x25, 0x5d, 0x05, 0xc9, 0xa5, 0x81, 0x06, 0xd2, 0x26, 0x24, 0xa9,
	0x5e, 0xfe, 0x7b, 0xc9, 0x0f, 0x11, 0xff, 0x80, 0x8e, 0xdf, 0x7b, 0xf0, 0xe5, 0xcb, 0x83, 0x3b,
	0x67, 0x44, 0xfa, 0x74, 0x5a, 0x49, 0x35, 0x3a, 0x6f, 0xa3, 0xa5, 0x9d, 0x9b, 0xd6, 0x1f, 0xb0,
	0x7a, 0x8d, 0x61, 0x6b, 0x44, 0xda, 0xe6, 0x0d, 0x7d, 0x80, 0x85, 0xb7, 0xf6, 0xb8, 0xd9, 0x33,
	0xd4, 0xa3, 0x01, 0xf3, 0x46, 0x94, 0xc1, 0xb5, 0x3c, 0x08, 0xed, 0x37, 0x7b, 0xd6, 0xf5, 0x68,
	0x20, 0xfc, 0x17, 0xe9, 0x0a, 0xd0, 0xcc, 0x70, 0x99, 0xa1, 0x39, 0x53, 0x62, 0x57, 0x95, 0x52,
	0xb6, 0xef, 0xa2, 0xbc, 0x94, 0xfd, 0x00, 0xb7, 0xbb, 0x28, 0xdf, 0xc4, 0x51, 0x71, 0x15, 0xce,
	0x26, 0x66, 0xfd, 0xb7, 0x3e, 0x9d, 0x94, 0x2f, 0x7a, 0xc2, 0x1b, 0xe5, 0xb9, 0xb1, 0x36, 0x28,
	0xdf, 0xec, 0x8d, 0xe8, 0x23, 0x2c, 0xcb, 0x3d, 0xde, 0x75, 0x88, 0x0c, 0xf7, 0x78, 0xb8, 0x79,
	0x5a, 0x8e, 0x6e, 0x1a, 0x4b, 0x2c, 0xff, 0xdb, 0xad, 0x5f, 0x80, 0xd4, 0x0f, 0xdc, 0x03, 0xf9,
	0x12, 0xe6, 0xac, 0xda, 0x03, 0x15, 0x6a, 0x64, 0xf7, 0x2f, 0xb2, 0x25, 0xa7, 0x69, 0x51, 0x6e,
	0xfd, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0x93, 0xfa, 0xda, 0x80, 0x7f, 0x01, 0x00, 0x00,
}
