// Code generated by protoc-gen-go. DO NOT EDIT.
// source: redis_user_login.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RedisUserLogin struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Token                []byte   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	TokenExpiredTime     int64    `protobuf:"varint,3,opt,name=tokenExpiredTime,proto3" json:"tokenExpiredTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisUserLogin) Reset()         { *m = RedisUserLogin{} }
func (m *RedisUserLogin) String() string { return proto.CompactTextString(m) }
func (*RedisUserLogin) ProtoMessage()    {}
func (*RedisUserLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_c41d9fe5ac1f4367, []int{0}
}

func (m *RedisUserLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisUserLogin.Unmarshal(m, b)
}
func (m *RedisUserLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisUserLogin.Marshal(b, m, deterministic)
}
func (m *RedisUserLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisUserLogin.Merge(m, src)
}
func (m *RedisUserLogin) XXX_Size() int {
	return xxx_messageInfo_RedisUserLogin.Size(m)
}
func (m *RedisUserLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisUserLogin.DiscardUnknown(m)
}

var xxx_messageInfo_RedisUserLogin proto.InternalMessageInfo

func (m *RedisUserLogin) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RedisUserLogin) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *RedisUserLogin) GetTokenExpiredTime() int64 {
	if m != nil {
		return m.TokenExpiredTime
	}
	return 0
}

func init() {
	proto.RegisterType((*RedisUserLogin)(nil), "pb.RedisUserLogin")
}

func init() { proto.RegisterFile("redis_user_login.proto", fileDescriptor_c41d9fe5ac1f4367) }

var fileDescriptor_c41d9fe5ac1f4367 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x4a, 0x4d, 0xc9,
	0x2c, 0x8e, 0x2f, 0x2d, 0x4e, 0x2d, 0x8a, 0xcf, 0xc9, 0x4f, 0xcf, 0xcc, 0xd3, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xca, 0xe2, 0xe2, 0x0b, 0x02, 0xc9, 0x86, 0x16, 0xa7,
	0x16, 0xf9, 0x80, 0xe4, 0x84, 0xc4, 0xb8, 0xd8, 0x40, 0x2a, 0x3d, 0x53, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x98, 0x83, 0xa0, 0x3c, 0x21, 0x11, 0x2e, 0xd6, 0x92, 0xfc, 0xec, 0xd4, 0x3c, 0x09, 0x26,
	0x05, 0x46, 0x0d, 0x9e, 0x20, 0x08, 0x47, 0x48, 0x8b, 0x4b, 0x00, 0xcc, 0x70, 0xad, 0x28, 0xc8,
	0x2c, 0x4a, 0x4d, 0x09, 0xc9, 0xcc, 0x4d, 0x95, 0x60, 0x06, 0xeb, 0xc3, 0x10, 0x4f, 0x62, 0x03,
	0x5b, 0x6b, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x31, 0x16, 0xf4, 0x90, 0x00, 0x00, 0x00,
}
