// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SERVICE int32

const (
	SERVICE_NULL  SERVICE = 0
	SERVICE_DB    SERVICE = 1
	SERVICE_LOGIN SERVICE = 2
	SERVICE_G001  SERVICE = 3
	SERVICE_GW    SERVICE = 4
)

var SERVICE_name = map[int32]string{
	0: "NULL",
	1: "DB",
	2: "LOGIN",
	3: "G001",
	4: "GW",
}

var SERVICE_value = map[string]int32{
	"NULL":  0,
	"DB":    1,
	"LOGIN": 2,
	"G001":  3,
	"GW":    4,
}

func (x SERVICE) String() string {
	return proto.EnumName(SERVICE_name, int32(x))
}

func (SERVICE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func init() {
	proto.RegisterEnum("pb.SERVICE", SERVICE_name, SERVICE_value)
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 102 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0xd2, 0xb2, 0xe0,
	0x62, 0x0f, 0x76, 0x0d, 0x0a, 0xf3, 0x74, 0x76, 0x15, 0xe2, 0xe0, 0x62, 0xf1, 0x0b, 0xf5, 0xf1,
	0x11, 0x60, 0x10, 0x62, 0xe3, 0x62, 0x72, 0x71, 0x12, 0x60, 0x14, 0xe2, 0xe4, 0x62, 0xf5, 0xf1,
	0x77, 0xf7, 0xf4, 0x13, 0x60, 0x02, 0x49, 0xba, 0x1b, 0x18, 0x18, 0x0a, 0x30, 0x83, 0x24, 0xdd,
	0xc3, 0x05, 0x58, 0x92, 0xd8, 0xc0, 0x86, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x77, 0xe6,
	0xd7, 0x56, 0x55, 0x00, 0x00, 0x00,
}
