// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_authentication.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CtsUserAuthentication struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Token                []byte   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	TokenExpireTime      int64    `protobuf:"varint,3,opt,name=tokenExpireTime,proto3" json:"tokenExpireTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CtsUserAuthentication) Reset()         { *m = CtsUserAuthentication{} }
func (m *CtsUserAuthentication) String() string { return proto.CompactTextString(m) }
func (*CtsUserAuthentication) ProtoMessage()    {}
func (*CtsUserAuthentication) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d3a9f6795e9c81b, []int{0}
}

func (m *CtsUserAuthentication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CtsUserAuthentication.Unmarshal(m, b)
}
func (m *CtsUserAuthentication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CtsUserAuthentication.Marshal(b, m, deterministic)
}
func (m *CtsUserAuthentication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CtsUserAuthentication.Merge(m, src)
}
func (m *CtsUserAuthentication) XXX_Size() int {
	return xxx_messageInfo_CtsUserAuthentication.Size(m)
}
func (m *CtsUserAuthentication) XXX_DiscardUnknown() {
	xxx_messageInfo_CtsUserAuthentication.DiscardUnknown(m)
}

var xxx_messageInfo_CtsUserAuthentication proto.InternalMessageInfo

func (m *CtsUserAuthentication) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CtsUserAuthentication) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *CtsUserAuthentication) GetTokenExpireTime() int64 {
	if m != nil {
		return m.TokenExpireTime
	}
	return 0
}

type StcUserAuthentication struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Result               string   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	SessionId            int64    `protobuf:"varint,3,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StcUserAuthentication) Reset()         { *m = StcUserAuthentication{} }
func (m *StcUserAuthentication) String() string { return proto.CompactTextString(m) }
func (*StcUserAuthentication) ProtoMessage()    {}
func (*StcUserAuthentication) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d3a9f6795e9c81b, []int{1}
}

func (m *StcUserAuthentication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StcUserAuthentication.Unmarshal(m, b)
}
func (m *StcUserAuthentication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StcUserAuthentication.Marshal(b, m, deterministic)
}
func (m *StcUserAuthentication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StcUserAuthentication.Merge(m, src)
}
func (m *StcUserAuthentication) XXX_Size() int {
	return xxx_messageInfo_StcUserAuthentication.Size(m)
}
func (m *StcUserAuthentication) XXX_DiscardUnknown() {
	xxx_messageInfo_StcUserAuthentication.DiscardUnknown(m)
}

var xxx_messageInfo_StcUserAuthentication proto.InternalMessageInfo

func (m *StcUserAuthentication) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *StcUserAuthentication) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *StcUserAuthentication) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func init() {
	proto.RegisterType((*CtsUserAuthentication)(nil), "pb.CtsUserAuthentication")
	proto.RegisterType((*StcUserAuthentication)(nil), "pb.StcUserAuthentication")
}

func init() { proto.RegisterFile("user_authentication.proto", fileDescriptor_2d3a9f6795e9c81b) }

var fileDescriptor_2d3a9f6795e9c81b = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x4d, 0x8b, 0xc2, 0x30,
	0x10, 0x40, 0x49, 0x4b, 0xcb, 0x36, 0x2c, 0x2c, 0x84, 0xed, 0xd2, 0x05, 0x0f, 0xa5, 0xa7, 0x9c,
	0xbc, 0xf8, 0x0b, 0x44, 0x3c, 0xf4, 0x1a, 0xf5, 0x2c, 0xfd, 0x18, 0x30, 0xa8, 0x49, 0xc9, 0x4c,
	0xc0, 0x9f, 0x2f, 0x8d, 0x01, 0x51, 0xbc, 0xcd, 0x7b, 0xcc, 0xf0, 0x18, 0xfe, 0xef, 0x11, 0xdc,
	0xb1, 0xf3, 0x74, 0x02, 0x43, 0x7a, 0xe8, 0x48, 0x5b, 0xb3, 0x9c, 0x9c, 0x25, 0x2b, 0x92, 0xa9,
	0x6f, 0x2c, 0x2f, 0x37, 0x84, 0x07, 0x04, 0xb7, 0x7e, 0x59, 0x11, 0x7f, 0x3c, 0x9f, 0x2f, 0xdb,
	0xb1, 0x62, 0x35, 0x93, 0x99, 0x8a, 0x24, 0x7e, 0x79, 0x46, 0xf6, 0x0c, 0xa6, 0x4a, 0x6a, 0x26,
	0xbf, 0xd5, 0x03, 0x84, 0xe4, 0x3f, 0x61, 0xd8, 0xde, 0x26, 0xed, 0x60, 0xaf, 0xaf, 0x50, 0xa5,
	0x35, 0x93, 0xa9, 0x7a, 0xd7, 0x0d, 0xf0, 0x72, 0x47, 0xc3, 0xe7, 0x20, 0x52, 0x47, 0x1e, 0x43,
	0xf0, 0x4b, 0x45, 0x9a, 0xbd, 0x03, 0xf4, 0x17, 0x0a, 0xc5, 0x42, 0x45, 0x12, 0x0b, 0x5e, 0x20,
	0x20, 0x6a, 0x6b, 0xda, 0x31, 0xc6, 0x9e, 0xa2, 0xcf, 0xc3, 0x8b, 0xab, 0x7b, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xfc, 0xff, 0x6f, 0x23, 0xff, 0x00, 0x00, 0x00,
}
