// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_enter.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CtsUserEnter struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RoomId               int64    `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CtsUserEnter) Reset()         { *m = CtsUserEnter{} }
func (m *CtsUserEnter) String() string { return proto.CompactTextString(m) }
func (*CtsUserEnter) ProtoMessage()    {}
func (*CtsUserEnter) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ea89c8060d2ffc2, []int{0}
}

func (m *CtsUserEnter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CtsUserEnter.Unmarshal(m, b)
}
func (m *CtsUserEnter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CtsUserEnter.Marshal(b, m, deterministic)
}
func (m *CtsUserEnter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CtsUserEnter.Merge(m, src)
}
func (m *CtsUserEnter) XXX_Size() int {
	return xxx_messageInfo_CtsUserEnter.Size(m)
}
func (m *CtsUserEnter) XXX_DiscardUnknown() {
	xxx_messageInfo_CtsUserEnter.DiscardUnknown(m)
}

var xxx_messageInfo_CtsUserEnter proto.InternalMessageInfo

func (m *CtsUserEnter) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CtsUserEnter) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type StcUserEnter struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RoomId               int64    `protobuf:"varint,3,opt,name=roomId,proto3" json:"roomId,omitempty"`
	ChairId              int32    `protobuf:"varint,4,opt,name=chairId,proto3" json:"chairId,omitempty"`
	Gold                 int64    `protobuf:"varint,5,opt,name=gold,proto3" json:"gold,omitempty"`
	HeadId               int64    `protobuf:"varint,6,opt,name=headId,proto3" json:"headId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StcUserEnter) Reset()         { *m = StcUserEnter{} }
func (m *StcUserEnter) String() string { return proto.CompactTextString(m) }
func (*StcUserEnter) ProtoMessage()    {}
func (*StcUserEnter) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ea89c8060d2ffc2, []int{1}
}

func (m *StcUserEnter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StcUserEnter.Unmarshal(m, b)
}
func (m *StcUserEnter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StcUserEnter.Marshal(b, m, deterministic)
}
func (m *StcUserEnter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StcUserEnter.Merge(m, src)
}
func (m *StcUserEnter) XXX_Size() int {
	return xxx_messageInfo_StcUserEnter.Size(m)
}
func (m *StcUserEnter) XXX_DiscardUnknown() {
	xxx_messageInfo_StcUserEnter.DiscardUnknown(m)
}

var xxx_messageInfo_StcUserEnter proto.InternalMessageInfo

func (m *StcUserEnter) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *StcUserEnter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StcUserEnter) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *StcUserEnter) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *StcUserEnter) GetGold() int64 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *StcUserEnter) GetHeadId() int64 {
	if m != nil {
		return m.HeadId
	}
	return 0
}

type CtsUserLeave struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ChairId              int32    `protobuf:"varint,2,opt,name=chairId,proto3" json:"chairId,omitempty"`
	RoomId               int64    `protobuf:"varint,3,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CtsUserLeave) Reset()         { *m = CtsUserLeave{} }
func (m *CtsUserLeave) String() string { return proto.CompactTextString(m) }
func (*CtsUserLeave) ProtoMessage()    {}
func (*CtsUserLeave) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ea89c8060d2ffc2, []int{2}
}

func (m *CtsUserLeave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CtsUserLeave.Unmarshal(m, b)
}
func (m *CtsUserLeave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CtsUserLeave.Marshal(b, m, deterministic)
}
func (m *CtsUserLeave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CtsUserLeave.Merge(m, src)
}
func (m *CtsUserLeave) XXX_Size() int {
	return xxx_messageInfo_CtsUserLeave.Size(m)
}
func (m *CtsUserLeave) XXX_DiscardUnknown() {
	xxx_messageInfo_CtsUserLeave.DiscardUnknown(m)
}

var xxx_messageInfo_CtsUserLeave proto.InternalMessageInfo

func (m *CtsUserLeave) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CtsUserLeave) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *CtsUserLeave) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type StcUserLeave struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RoomId               int64    `protobuf:"varint,3,opt,name=roomId,proto3" json:"roomId,omitempty"`
	ChairId              int32    `protobuf:"varint,4,opt,name=chairId,proto3" json:"chairId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StcUserLeave) Reset()         { *m = StcUserLeave{} }
func (m *StcUserLeave) String() string { return proto.CompactTextString(m) }
func (*StcUserLeave) ProtoMessage()    {}
func (*StcUserLeave) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ea89c8060d2ffc2, []int{3}
}

func (m *StcUserLeave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StcUserLeave.Unmarshal(m, b)
}
func (m *StcUserLeave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StcUserLeave.Marshal(b, m, deterministic)
}
func (m *StcUserLeave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StcUserLeave.Merge(m, src)
}
func (m *StcUserLeave) XXX_Size() int {
	return xxx_messageInfo_StcUserLeave.Size(m)
}
func (m *StcUserLeave) XXX_DiscardUnknown() {
	xxx_messageInfo_StcUserLeave.DiscardUnknown(m)
}

var xxx_messageInfo_StcUserLeave proto.InternalMessageInfo

func (m *StcUserLeave) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *StcUserLeave) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *StcUserLeave) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func init() {
	proto.RegisterType((*CtsUserEnter)(nil), "pb.CtsUserEnter")
	proto.RegisterType((*StcUserEnter)(nil), "pb.StcUserEnter")
	proto.RegisterType((*CtsUserLeave)(nil), "pb.CtsUserLeave")
	proto.RegisterType((*StcUserLeave)(nil), "pb.StcUserLeave")
}

func init() { proto.RegisterFile("user_enter.proto", fileDescriptor_8ea89c8060d2ffc2) }

var fileDescriptor_8ea89c8060d2ffc2 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2d, 0x4e, 0x2d,
	0x8a, 0x4f, 0xcd, 0x2b, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48,
	0x52, 0xb2, 0xe3, 0xe2, 0x71, 0x2e, 0x29, 0x0e, 0x2d, 0x4e, 0x2d, 0x72, 0x05, 0xc9, 0x08, 0x89,
	0x71, 0xb1, 0x81, 0xd4, 0x79, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x41, 0x79, 0x20,
	0xf1, 0xa2, 0xfc, 0xfc, 0x5c, 0xcf, 0x14, 0x09, 0x26, 0x88, 0x38, 0x84, 0xa7, 0x34, 0x83, 0x91,
	0x8b, 0x27, 0xb8, 0x24, 0x99, 0xb0, 0x01, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x60, 0xed,
	0x9c, 0x41, 0x60, 0x36, 0x92, 0xa1, 0xcc, 0xc8, 0x86, 0x0a, 0x49, 0x70, 0xb1, 0x27, 0x67, 0x24,
	0x66, 0x82, 0x0c, 0x61, 0x51, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x71, 0x41, 0xa6, 0xa4, 0xe7, 0xe7,
	0xa4, 0x48, 0xb0, 0x82, 0xd5, 0x83, 0xd9, 0x20, 0x53, 0x32, 0x52, 0x13, 0x53, 0x3c, 0x53, 0x24,
	0xd8, 0x20, 0xa6, 0x40, 0x78, 0x4a, 0x11, 0x70, 0xaf, 0xf9, 0xa4, 0x26, 0x96, 0xa5, 0xe2, 0x74,
	0x19, 0x92, 0x6d, 0x4c, 0xa8, 0xb6, 0xe1, 0x70, 0x1f, 0xc8, 0x64, 0xa8, 0x9f, 0xf1, 0x9b, 0x4c,
	0xb2, 0xff, 0x92, 0xd8, 0xc0, 0x31, 0x63, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x60, 0xff, 0x1a,
	0xc2, 0xad, 0x01, 0x00, 0x00,
}
