// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_ready.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CtsUserReady struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	ChairId              int32    `protobuf:"varint,2,opt,name=chairId,proto3" json:"chairId,omitempty"`
	Status               bool     `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CtsUserReady) Reset()         { *m = CtsUserReady{} }
func (m *CtsUserReady) String() string { return proto.CompactTextString(m) }
func (*CtsUserReady) ProtoMessage()    {}
func (*CtsUserReady) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab94b23b5d4aad3e, []int{0}
}

func (m *CtsUserReady) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CtsUserReady.Unmarshal(m, b)
}
func (m *CtsUserReady) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CtsUserReady.Marshal(b, m, deterministic)
}
func (m *CtsUserReady) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CtsUserReady.Merge(m, src)
}
func (m *CtsUserReady) XXX_Size() int {
	return xxx_messageInfo_CtsUserReady.Size(m)
}
func (m *CtsUserReady) XXX_DiscardUnknown() {
	xxx_messageInfo_CtsUserReady.DiscardUnknown(m)
}

var xxx_messageInfo_CtsUserReady proto.InternalMessageInfo

func (m *CtsUserReady) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *CtsUserReady) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *CtsUserReady) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type StcUserReady struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	ChairId              int32    `protobuf:"varint,2,opt,name=chairId,proto3" json:"chairId,omitempty"`
	Status               bool     `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StcUserReady) Reset()         { *m = StcUserReady{} }
func (m *StcUserReady) String() string { return proto.CompactTextString(m) }
func (*StcUserReady) ProtoMessage()    {}
func (*StcUserReady) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab94b23b5d4aad3e, []int{1}
}

func (m *StcUserReady) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StcUserReady.Unmarshal(m, b)
}
func (m *StcUserReady) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StcUserReady.Marshal(b, m, deterministic)
}
func (m *StcUserReady) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StcUserReady.Merge(m, src)
}
func (m *StcUserReady) XXX_Size() int {
	return xxx_messageInfo_StcUserReady.Size(m)
}
func (m *StcUserReady) XXX_DiscardUnknown() {
	xxx_messageInfo_StcUserReady.DiscardUnknown(m)
}

var xxx_messageInfo_StcUserReady proto.InternalMessageInfo

func (m *StcUserReady) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *StcUserReady) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *StcUserReady) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*CtsUserReady)(nil), "pb.CtsUserReady")
	proto.RegisterType((*StcUserReady)(nil), "pb.StcUserReady")
}

func init() { proto.RegisterFile("user_ready.proto", fileDescriptor_ab94b23b5d4aad3e) }

var fileDescriptor_ab94b23b5d4aad3e = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2d, 0x4e, 0x2d,
	0x8a, 0x2f, 0x4a, 0x4d, 0x4c, 0xa9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48,
	0x52, 0x8a, 0xe0, 0xe2, 0x71, 0x2e, 0x29, 0x0e, 0x2d, 0x4e, 0x2d, 0x0a, 0x02, 0xc9, 0x08, 0x89,
	0x71, 0xb1, 0x15, 0xe5, 0xe7, 0xe7, 0x7a, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x41,
	0x79, 0x42, 0x12, 0x5c, 0xec, 0xc9, 0x19, 0x89, 0x99, 0x45, 0x9e, 0x29, 0x12, 0x4c, 0x0a, 0x8c,
	0x1a, 0xac, 0x41, 0x30, 0x2e, 0x48, 0x47, 0x71, 0x49, 0x62, 0x49, 0x69, 0xb1, 0x04, 0xb3, 0x02,
	0xa3, 0x06, 0x47, 0x10, 0x94, 0x07, 0x32, 0x39, 0xb8, 0x24, 0x99, 0x06, 0x26, 0x27, 0xb1, 0x81,
	0x9d, 0x6f, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x97, 0x17, 0xac, 0xe8, 0xd2, 0x00, 0x00, 0x00,
}
