// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_enter.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CtsUserEnter struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Token                []byte   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CtsUserEnter) Reset()         { *m = CtsUserEnter{} }
func (m *CtsUserEnter) String() string { return proto.CompactTextString(m) }
func (*CtsUserEnter) ProtoMessage()    {}
func (*CtsUserEnter) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ea89c8060d2ffc2, []int{0}
}

func (m *CtsUserEnter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CtsUserEnter.Unmarshal(m, b)
}
func (m *CtsUserEnter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CtsUserEnter.Marshal(b, m, deterministic)
}
func (m *CtsUserEnter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CtsUserEnter.Merge(m, src)
}
func (m *CtsUserEnter) XXX_Size() int {
	return xxx_messageInfo_CtsUserEnter.Size(m)
}
func (m *CtsUserEnter) XXX_DiscardUnknown() {
	xxx_messageInfo_CtsUserEnter.DiscardUnknown(m)
}

var xxx_messageInfo_CtsUserEnter proto.InternalMessageInfo

func (m *CtsUserEnter) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CtsUserEnter) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

type StcUserEnter struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Result               string   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StcUserEnter) Reset()         { *m = StcUserEnter{} }
func (m *StcUserEnter) String() string { return proto.CompactTextString(m) }
func (*StcUserEnter) ProtoMessage()    {}
func (*StcUserEnter) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ea89c8060d2ffc2, []int{1}
}

func (m *StcUserEnter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StcUserEnter.Unmarshal(m, b)
}
func (m *StcUserEnter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StcUserEnter.Marshal(b, m, deterministic)
}
func (m *StcUserEnter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StcUserEnter.Merge(m, src)
}
func (m *StcUserEnter) XXX_Size() int {
	return xxx_messageInfo_StcUserEnter.Size(m)
}
func (m *StcUserEnter) XXX_DiscardUnknown() {
	xxx_messageInfo_StcUserEnter.DiscardUnknown(m)
}

var xxx_messageInfo_StcUserEnter proto.InternalMessageInfo

func (m *StcUserEnter) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *StcUserEnter) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*CtsUserEnter)(nil), "pb.CtsUserEnter")
	proto.RegisterType((*StcUserEnter)(nil), "pb.StcUserEnter")
}

func init() { proto.RegisterFile("user_enter.proto", fileDescriptor_8ea89c8060d2ffc2) }

var fileDescriptor_8ea89c8060d2ffc2 = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2d, 0x4e, 0x2d,
	0x8a, 0x4f, 0xcd, 0x2b, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48,
	0x52, 0xb2, 0xe1, 0xe2, 0x71, 0x2e, 0x29, 0x0e, 0x2d, 0x4e, 0x2d, 0x72, 0x05, 0xc9, 0x08, 0x89,
	0x71, 0xb1, 0x81, 0xd4, 0x79, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x41, 0x79, 0x42,
	0x22, 0x5c, 0xac, 0x25, 0xf9, 0xd9, 0xa9, 0x79, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x10,
	0x8e, 0x92, 0x1d, 0x17, 0x4f, 0x70, 0x49, 0x32, 0x61, 0xdd, 0x62, 0x5c, 0x6c, 0x45, 0xa9, 0xc5,
	0xa5, 0x39, 0x25, 0x60, 0xed, 0x9c, 0x41, 0x50, 0x5e, 0x12, 0x1b, 0xd8, 0x21, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xcf, 0xe2, 0x89, 0xba, 0x9c, 0x00, 0x00, 0x00,
}
